### ISSUE TITLE
Why not make it compatible with Linux/Windows and Python 2/3?

### ISSUE THREAD

**Issue by shenwei356** [Eslam-Samir-Ragab/Sequence-database-curator#1]

**Comment by Eslam-Samir-Ragab** [comment]
@shenwei356 
I have just unified one file for the usage in Linux/Windows based on your suggestion, so thank you very much for drawing my attention for this issue 

I will work on making it compatible for both python 2 and 3
Thanks again for helping improving it and giving me the experience to do so

**Comment by shenwei356** [comment]
May it helps: [Cheat Sheet: Writing Python 2-3 compatible code](http://python-future.org/compatible_idioms.html)

Some other advice on the README.md:

- add `#!/usr/bin/env python` to the first line of script, so users can directly by script name.
- no need to duplicate usages for python 2 and 3, they should be the same.
- example codes should be formatted by "````" or indent of tab/4-spaces, not ">"

**Comment by Eslam-Samir-Ragab** [comment]
@shenwei356 
Thanks a lot for this help again.
I hope it is better now despite more dependencies that were added for the python 2/3 compatibility.

**Comment by shenwei356** [comment]
You add `from __future__ import print_function`, where `__future__` is standard library, no extra dependencies are added. 

Someone like to use `six`, which we can also install via `pip`
